name: CI - Lint / Tests / Deploy
on: [push]
jobs:
  lint:
    runs-on: ubuntu-20.04
    
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: lint with flake8
        run: |
          #stop the build if there are Python syntax erros or undefined names
          flake8 . --count --select=E9,f63,f7,f82 --show-source --statistics
          #exit-zero treats all erros as warnings. The github editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  tests:
    needs: lint
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.5, 3.6, 3.7, 3.8, 3.9]
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: deploy into heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key:${{secrets.HEROKU_API_KEY}}
          heroku_app_name:${{secrets.HEROKU_APP_NAME}}
          heroku_email:${{secrets.HEROKU_USER_EMAIL}}